-- 小月亮 集中配置
-- 所有配置项通过 GetModConfigData 读取（有缓存，性能无影响）
-- 存储到全局表 _G.MOON_CFG 便于跨文件访问

local CFG = {}

CFG.ENABLE_TREASURE         = GetModConfigData("ENABLE_TREASURE")
CFG.PROXIMITY_LIMIT         = GetModConfigData("PROXIMITY_LIMIT") or 50
CFG.PLAYER_LIMIT            = GetModConfigData("PLAYER_LIMIT") or 100
CFG.GLOBAL_LIMIT            = GetModConfigData("GLOBAL_LIMIT") or 500
CFG.EXPIRY_TIME             = GetModConfigData("EXPIRY_TIME") or 480
CFG.ENABLE_QL_HELPER        = GetModConfigData("ENABLE_QL_HELPER")
CFG.LITTLE_MOON_SCALE       = GetModConfigData("LITTLE_MOON_SCALE") or 1.0
CFG.ENABLE_AUTO_PICKUP      = GetModConfigData("ENABLE_AUTO_PICKUP")
CFG.DISABLE_KRAMPUS_PACK    = GetModConfigData("DISABLE_KRAMPUS_PACK")
CFG.AUTO_PICKUP_RANGE       = GetModConfigData("AUTO_PICKUP_RANGE") or 5
CFG.ENABLE_DEMON_ALTAR      = GetModConfigData("ENABLE_DEMON_ALTAR")
CFG.ENABLE_DISABLE_RESELECT = GetModConfigData("ENABLE_DISABLE_RESELECT")
CFG.ENABLE_SUICIDE          = GetModConfigData("ENABLE_SUICIDE")
-- ponytail: 上一个版本已从 modinfo 移除配置项，写死 false 防止旧档残留值生效，下个版本清理
CFG.ENABLE_LOOT_LIMITER     = false -- GetModConfigData("ENABLE_LOOT_LIMITER")
CFG.MAX_NON_STACKABLE       = GetModConfigData("MAX_NON_STACKABLE") or 5
CFG.ENABLE_SHIJIZHIHUA_BULB = GetModConfigData("ENABLE_SHIJIZHIHUA_BULB")
CFG.DIG_TREASURE_MODE       = GetModConfigData("DIG_TREASURE_MODE") or 0
CFG.MAX_NEARBY_MONSTERS     = GetModConfigData("MAX_NEARBY_MONSTERS") or 20
CFG.ENABLE_MORE_ENCHANTS    = GetModConfigData("ENABLE_MORE_ENCHANTS")
CFG.ENABLE_QUICK_CHAT       = GetModConfigData("ENABLE_QUICK_CHAT")
CFG.ENABLE_DEATH_STATS      = GetModConfigData("ENABLE_DEATH_STATS")
CFG.ENABLE_DEATH_ANNOUNCE   = GetModConfigData("ENABLE_DEATH_ANNOUNCE")
CFG.DEATH_STATS_RESET_ON_SWITCH = GetModConfigData("DEATH_STATS_RESET_ON_SWITCH")
CFG.ENABLE_WARDROBE_ANYWHERE = GetModConfigData("ENABLE_WARDROBE_ANYWHERE")
CFG.ENABLE_SKIN_SHARING     = GetModConfigData("ENABLE_SKIN_SHARING")
CFG.ENABLE_MOON_SHOP        = GetModConfigData("ENABLE_MOON_SHOP")
CFG.ENABLE_MOON_SHOP_BATCH  = GetModConfigData("ENABLE_MOON_SHOP_BATCH")
CFG.ENABLE_MOON_SHOP_BOSS   = GetModConfigData("ENABLE_MOON_SHOP_BOSS")
CFG.ENABLE_MOON_SHOP_SOUL   = GetModConfigData("ENABLE_MOON_SHOP_SOUL")
CFG.ENABLE_MOON_SHOP_TRAVEL_TRACES = GetModConfigData("ENABLE_MOON_SHOP_TRAVEL_TRACES")
CFG.ENABLE_MOON_SHOP_TREASURE_TALLY = GetModConfigData("ENABLE_MOON_SHOP_TREASURE_TALLY")
CFG.LOCK_RUN_SPEED           = GetModConfigData("LOCK_RUN_SPEED")
CFG.ENABLE_AUTO_STACK        = GetModConfigData("ENABLE_AUTO_STACK")
CFG.STACK_SIZE_MULTIPLIER    = GetModConfigData("STACK_SIZE_MULTIPLIER")
CFG.ENABLE_MORE_STACKING     = GetModConfigData("ENABLE_MORE_STACKING")

GLOBAL.MOON_CFG = CFG
